### PR TITLE
increase recursion limit patch for 455, 46

### PR DESCRIPTION
**Pull request by Vladimir-Antonovich**

### CODE REVIEW

**Review by tyacbovi — APPROVED** [review]

**Review by tyacbovi — CHANGES_REQUESTED** [review]
Look that 4.6 is not in the patch

**Comment by geokala** [comment]
@tyacbovi There is a 4.6 version of the patch, it's the second one down.
We could combine them both into one file I think, but it's probably not hugely important, especially if someone is waiting for the patch.

**Comment by geokala** [comment]
Worth noting though that it's not been added to the registry. Is this intentional?

**Review by tyacbovi — APPROVED** [review]

**Comment by jrzeszutek** [comment]
Hi @tyacbovi @isaac-s I experience some issues after this commit. When I try to update my manager with the recommended patches, update fails because this patch seems to collide with 4_6_use_concat_everywhere. Hashes mismatch. Please take a look on the log files. One is the output of "./patchify manager-updates apply" and another one is from separate installation of both patches (first one installs successfully, but the second one fails).

[manager_updates.txt](https://github.com/cloudify-cosmo/patchify/files/3447212/manager_updates.txt)

[separate_installations.txt](https://github.com/cloudify-cosmo/patchify/files/3447211/separate_installations.txt)

**Comment by geokala** [comment]
Fix incoming shortly.

**Comment by geokala** [comment]
Fix is in https://github.com/cloudify-cosmo/patchify/pull/110/files, should be reviewed shortly.
Longer term avoidance of this issue is under discussion.

**Comment by geokala** [comment]
@jrzeszutek It should be working again now, assuming github has synced raw.githubusercontent.com in a timely manner.

**Comment by jrzeszutek** [comment]
@geokala Thanks! It works now.

**Pull request merged**
