### PR TITLE
Add the 'smart install resume' patch to 4.6

### PR DESCRIPTION
**Pull request by tehasdf**
This adds the "smart resume of the install workflow" feature to 4.6.

When an install workflow is resumed:
- if we are going to re-send the create operation, send delete first
- if we are going to re-send the start operation, send stop first
- if the delete or stop fails, just ignore that failure, and continue with the resume.

### CODE REVIEW

**Comment by tehasdf** [comment]
To test this, create a blueprint which contains a create operation that can fail.
When it fails, resume that execution and note that we now send a delete first.

Similar with the start operation.

**Comment by tehasdf** [comment]
the 5.1 counterpart to this is cloudify-cosmo/cloudify-common#548

**Comment by tehasdf** [comment]
Updated the patch now with fixed ignoring the errors in cleanup (uninstall), there should now be no retries in the cleanup tasks

**Comment by tehasdf** [comment]
Appended this change to the patch cloudify-cosmo/cloudify-common#551

**Review by geokala — APPROVED** [review]

**Pull request merged**
