### PR TITLE
CY-1904 4.6: Don't write to the db when replicating AMQP resources

### PR DESCRIPTION
**Pull request by tehasdf**
sync_metadata is supposed to replicate AMQP resources, ie. vhosts and
users in rabbitmq.
However, by just using raw sync_metadata, it can happen that agents
might need to be updated (if they were restored and reinstalled from
a snapshot that didn't have per-agent amqp credentials).

In that case, sync_metadata will attempt to update them, but that is
the wrong time to do so, because the database might not be open for
writes (yet).

Instead, let's not issue writes. If the agents were not updated by
the snapshot procedure, they were not meant to be updated (especially
by something unrelated, like this).

### CODE REVIEW

**Comment by geokala** [comment]
What is the effect of not updating the DB? Does it in some way get updated later, or is it already updated in this case because of coming from a snapshot?

**Comment by tehasdf** [comment]
@geokala it is either already updated, or will never be updated, and the rest of the system needs to cope with either (by using per-agent credentials, or per-tenant credentials)
Either way, a failover is the wrong place to update this, and this change is only about making failover do no updates to the db

**Comment by tehasdf** [comment]
The changes in this patch can be viewed more nicely in the original commits:
https://github.com/cloudify-cosmo/cloudify-manager/commit/bc53d1393cff994fdf3ba7cf07a7efc1e19bb058
https://github.com/cloudify-cosmo/cloudify-premium/commit/9d1c2d1fab1aa8c1e6ab95d6c5f656825d46e83e

**Comment by tehasdf** [comment]
Test procedure:
1. Create a 4.5 manager, install an agent, create a snapshot
2. Create a 4.6 cluster, and restore that snapshot (remember, snapshot needs to be restored before adding replicas)
3. Do `sudo -upostgres psql cloudify_db --port 15432  -c 'select * from agents'`, and note that one agent exists, with state=restored, and with empty rabbitmq_username & rabbitmq_password
4. Run `cfy agents install`
5. Select agents again, and note that a new agent is inserted, with state=upgraded, and one that does have a rabbitmq_username & rabbitmq_password
6. Do a failover (by doing eg. `cfy cluster set-active`)
7. Examine rabbitmq journal log on the replica that is becoming the master (`journalctl -u cloudify-rabbitmq`)

Without this patch, the following will be true, and all signify a failure:
 - in the rabbitmq log, we see an error from the post-start operation, eg. 
```Nov 08 11:48:40 cloudify rabbitmq_replication[17326]: manager_rest.manager_exceptions.SQLStorageException: SQL Storage error: (psycopg2.InternalError) cannot execute UPDATE in a read-only transaction
Nov 08 11:48:40 cloudify rabbitmq_replication[17326]: [SQL: 'UPDATE agents SET rabbitmq_username=%(rabbitmq_username)s, rabbitmq_password=%(rabbitmq_password)s WHERE agents._storage_id = %(agents__storage_id)s'] 
[parameters: {'rabbitmq_password': 'gAAAAABdxVYY8rvD18V6rlJw-4MM84Qyo2YVWYceR3xF_8Bl1TE5eLxhOkpAOimD7WfM85mNFBzATi3by7w-GTDYDKpPn2PSND63tQkrqh4NX8zEuKRbnCo1DQN7ekPLkOR0n6G6vpP8', 'rabbitmq_username': 'rabbitmq_us
er_vm_fhp447', 'agents__storage_id': 1}] (Background on this error at: http://sqlalche.me/e/2j85)
```
 - in the `select * from agents`, we see that the "restored" agent now has rabbitmq_username and rabbitmq_credentials
 - in `rabbitmqctl -n cloudify-manager@localhost list_users` we see that a rabbitmq user was created for the restored agent (called `rabbitmq_user_agent_name`). I mean that a user for the _restored_ agent must not exist, a user for the _upgraded_ agent must of course exist
 - the failover was either successful or the previous leader remained the leader, this depends on a race

Example on a patched manager, after a failover:
```
[root@cloudify /]# sudo -upostgres psql cloudify_db --port 15432 -c 'select name, rabbitmq_username from agents'
                      name                      |                      rabbitmq_username                       
------------------------------------------------+--------------------------------------------------------------
 vm_c259cf_326b07a6-d4e9-48b6-afa8-1581ffb66f2f | rabbitmq_user_vm_c259cf_326b07a6-d4e9-48b6-afa8-1581ffb66f2f
 vm_c259cf                                      | 
(2 wiersze)

[root@cloudify /]# rabbitmqctl -n cloudify-manager@localhost list_users
Listing users ...
rabbitmq_user_vm_c259cf_326b07a6-d4e9-48b6-afa8-1581ffb66f2f    []
cloudify        [administrator]
rabbitmq_user_default_tenant    []
[root@cloudify /]# 
```

**Comment by geokala** [comment]
I'm not seeing the agent in a restored state: 

```bash
[centos@cloudify ~]$ sudo -upostgres psql cloudify_db --port 15432 -c 'select * from agents'
could not change directory to "/home/centos": Permission denied
 _storage_id | id | name | ip | install_method | system | version | state | visibility | rabbitmq_username | rabbitmq_password | rabbitmq_exchange | created_at | updated_at | _node_instance_fk | _tenant_id | _cre
ator_id 
-------------+----+------+----+----------------+--------+---------+-------+------------+-------------------+-------------------+-------------------+------------+------------+-------------------+------------+-----
--------
(0 rows)
```

**Comment by geokala** [comment]
Still nothing in that table after the agents install

**Comment by geokala** [comment]
Ah- I think I know the problem. The hello-world example doesn't actually use agents. <headdesk>

**Comment by geokala** [comment]
Looks good when tested with an appropriate blueprint, approving.

**Review by geokala — APPROVED** [review]

**Pull request merged**
