### PR TITLE
Add the reevaluate-operations patch to 4.6

### PR DESCRIPTION
**Pull request by tehasdf**

### CODE REVIEW

**Comment by tehasdf** [comment]
Example test procedure:
Use the blueprint from https://gist.github.com/tehasdf/9673ee5719505e54ae0685fe98456a79
(this is the same blueprint as used in integration tests). This blueprint creates 2 node instances, and in install, fails or succeeds depending on an input, and sets an input value in runtime-properties (in several places, pulling from either node properties, or from operation inputs).


1. Upload the blueprint
2. Create a deployment, passing inputs: input1=some_value, fail_create=some_truthy_value
```bash
cfy dep cre -bb1 d1 -iinput1=1 -ifail_create=1
```
3. Run the install workflow. It will fail on the create operation due to fail_create being enabled
```bash
cfy exe sta -dd1 install
```
4. Update the deployment, changing the input values, and reevaluating operations
```bash
cfy dep up d1 -iinput1=2 -ifail_create='' --update-executions
```
(note that this patch adds `--update-executions` to the on-manager CLI, but this flag isn't available in other 4.6 CLI's, eg. on your laptop)
5. Resume the failed install workflow. If the inputs were changed, the workflow will succeed.
6. Check using `cfy node-instances get` and `cfy dep outputs` that values do use the changed input value (eg. "2") and not the original value (eg. "1")

**Comment by tehasdf** [comment]
This ports CY-1710 to 4.6

**Comment by tehasdf** [comment]
This doesn't include the central registry entry yet, but eventually will, when this is tested and approved

**Review by geokala — APPROVED** [review]

**Comment by tehasdf** [comment]
This patch has been updated, and the `--update-operations` flag no longer exists, but the new behaviour is the default.

**Comment by isaac-s** [comment]
@tehasdf customer approved the patch.
Please merge this to Patchify so it's in the central repository.

**Pull request merged**
